name: 'check-files'
'on': pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: danieljimeneznz/ensure-files-changed@v4.0.1
        with:
          require-changes-to:
            - "dist/index.js"
            - "CHANGELOG.md"
          prevent-changes-to:
            - "LICENSE.md"
          token: ${{ secrets.GITHUB_TOKEN }}
